In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [143]:
colors = ["#C37681", "#EAE086", "#838385", "#89C1DF", "#5BAC82"]
# Set your custom color palette
sns.set_palette(sns.color_palette(colors))

In [2]:
bdi3_df = pd.read_csv('../data/teis.csv', dtype = {"Child ID" : object, "Cognitive T-Score" : object})

In [3]:
bdi3_df = bdi3_df.drop(columns = {'Code 1', 'Code 2', 'Code 3', 'Code 4', 'Code 5', 'Code 6', 'Code 7', 'Code 8', 'Code 9', 'Code 10'}, axis =0)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
bdi3_df

Child ID Gender Date of Birth Location - Sub Level 1  \
0        44879      F    2022-09-27              Southwest   
1        47795      F    2020-12-23      Greater Nashville   
2        54340      M    2021-06-22        First Tennessee   
3        54344      F    2022-03-07    Southeast Tennessee   
4        54515      M    2021-11-04          Memphis Delta   
...        ...    ...           ...                    ...   
23942  SP03287      F    2023-09-25          Memphis Delta   
23943  SP03288      F    2021-05-18          South Central   
23944  SP03289      F    2021-10-31          South Central   
23945  SP03290      M    2020-03-25          Memphis Delta   
23946  SP03291      M    2023-09-18      Greater Nashville   

                      Program Label  Adaptive Sum of Scaled Scores  \
0      BDI-3 Eligibility Evaluation                            7.0   
1      BDI-3 Eligibility Evaluation                           16.0   
2      BDI-3 Eligibility Evaluation                            8.0   
3      BDI-3 Eligibility Evaluation                           13.0   
4      BDI-3 Eligibility Evaluation                            5.0   
...                             ...                            ...   
23942  BDI-3 Eligibility Evaluation                           13.0   
23943  BDI-3 Eligibility Evaluation                           25.0   
23944  BDI-3 Eligibility Evaluation                           21.0   
23945       BDI-3 Annual Evaluation                           16.0   
23946  BDI-3 Eligibility Evaluation                           11.0   

       Adaptive Developmental Quotient  Adaptive Percentile Rank  \
0                                 85.0                      16.0   
1                                 88.0                      21.0   
2                                 90.0                      25.0   
3                                115.0                      84.0   
4                                 75.0                       5.0   
...                                ...                       ...   
23942                            115.0                      84.0   
23943                            115.0                      84.0   
23944                            103.0                      58.0   
23945                             88.0                      21.0   
23946                            105.0                      63.0   

      Adaptive 95% Confidence Interval         Adaptive RDI Adaptive Z-Score  \
0                                77-97                39/90            1.00   
1                                82-96                79/90            0.80   
2                               81-101                77/90            0.67   
3                              103-123                99/90                1   
4                                68-88  1990-09-01 00:00:00            1.67   
...                                ...                  ...              ...   
23942                          103-123                99/90                1   
23943                          107-121                96/90                1   
23944                           96-110                92/90              0.2   
23945                            82-96                66/90            0.80   
23946                           94-114                94/90             0.33   

       Adaptive T-Score Adaptive NCE  Social-Emotional Sum of Scaled Scores  \
0                  40.0           29                                   29.0   
1                  42.0           33                                   32.0   
2                  43.0           36                                   17.0   
3                  60.0           71                                   21.0   
4                  33.0           15                                   11.0   
...                 ...          ...                                    ...   
23942              60.0           71                                   25.0   
23943     

Eligibility is currently based on domains. A child would be considered eligible based on a 40% delay in one area or 25% delay in two areas, as determined by Development Quotient (DQ) scores. A DQ of 70 or less indicates a 40% delay, and a DQ between 71 and 78 indicates a 25% delay. If TEIS added an option for eligibility based on the total score on the BDI-3 total score (DQ score of 70 or less), are there any children who would have qualified that did not qualify based on the current method?

In [6]:
bdi3_df['Standard Approval'] = ''
bdi3_df['Extended Approval'] = ''

columns = [col for col in bdi3_df.columns if 'Developmental Quotient' in col]

columns
#added two new columns. Now I want to loop through and see which students scored a domain DQ of under 70 OR two domain DQ between 71-78


    

['Adaptive Developmental Quotient',
 'Social-Emotional Developmental Quotient',
 'Communication Developmental Quotient',
 'Motor Developmental Quotient',
 'Cognitive Developmental Quotient',
 'BDI-3 Total Developmental Quotient']

In [7]:
bdi3_df['Adaptive DQ Points'] = ''
bdi3_df['Social-Emotional DQ Points'] = ''
bdi3_df['Communication DQ Points'] = ''
bdi3_df['Motor DQ Points'] = ''
bdi3_df['Cognitive DQ Points'] = ''

In [8]:
bdi3_df['Adaptive Developmental Quotient']

0         85.0
1         88.0
2         90.0
3        115.0
4         75.0
         ...  
23942    115.0
23943    115.0
23944    103.0
23945     88.0
23946    105.0
Name: Adaptive Developmental Quotient, Length: 23947, dtype: float64

In [9]:
# bdi3_df.loc[bdi3_df.loc['Adaptive Developmental Quotient'] <= 70, 'Adaptive DQ Points'] = 2
# bdi3_df.loc[bdi3_df.loc['Adaptive Developmental Quotient'] > 70, 'Adaptive DQ Points'] = 0
# bdi3_df.loc[(bdi3_df.loc['Adaptive Developmental Quotient'] <= 71) & (bdi3_df.loc['Adaptive Developmental Quotient'] <= 71), 'Adaptive DQ Points'] = 1

In [10]:
bdi3_df['Adaptive DQ Points'] = bdi3_df['Adaptive Developmental Quotient'].apply(lambda x: 2 if x <= 70 else 1 if 71 <= x <= 78 else 0)
bdi3_df['Social-Emotional DQ Points'] = bdi3_df['Social-Emotional Developmental Quotient'].apply(lambda x: 2 if x <= 70 else 1 if 71 <= x <= 78 else 0)
bdi3_df['Communication DQ Points'] = bdi3_df['Communication Developmental Quotient'].apply(lambda x: 2 if x <= 70 else 1 if 71 <= x <= 78 else 0)
bdi3_df['Motor DQ Points'] = bdi3_df['Motor Developmental Quotient'].apply(lambda x: 2 if x <= 70 else 1 if 71 <= x <= 78 else 0)
bdi3_df['Cognitive DQ Points'] = bdi3_df['Cognitive Developmental Quotient'].apply(lambda x: 2 if x <= 70 else 1 if 71 <= x <= 78 else 0)

In [11]:
points_cols = ['Adaptive DQ Points', 'Social-Emotional DQ Points', 'Communication DQ Points', 'Motor DQ Points', 'Cognitive DQ Points']
bdi3_df['bdi3_df_points'] = bdi3_df[points_cols].sum(axis = 1)
bdi3_df

Child ID Gender Date of Birth Location - Sub Level 1  \
0        44879      F    2022-09-27              Southwest   
1        47795      F    2020-12-23      Greater Nashville   
2        54340      M    2021-06-22        First Tennessee   
3        54344      F    2022-03-07    Southeast Tennessee   
4        54515      M    2021-11-04          Memphis Delta   
...        ...    ...           ...                    ...   
23942  SP03287      F    2023-09-25          Memphis Delta   
23943  SP03288      F    2021-05-18          South Central   
23944  SP03289      F    2021-10-31          South Central   
23945  SP03290      M    2020-03-25          Memphis Delta   
23946  SP03291      M    2023-09-18      Greater Nashville   

                      Program Label  Adaptive Sum of Scaled Scores  \
0      BDI-3 Eligibility Evaluation                            7.0   
1      BDI-3 Eligibility Evaluation                           16.0   
2      BDI-3 Eligibility Evaluation                            8.0   
3      BDI-3 Eligibility Evaluation                           13.0   
4      BDI-3 Eligibility Evaluation                            5.0   
...                             ...                            ...   
23942  BDI-3 Eligibility Evaluation                           13.0   
23943  BDI-3 Eligibility Evaluation                           25.0   
23944  BDI-3 Eligibility Evaluation                           21.0   
23945       BDI-3 Annual Evaluation                           16.0   
23946  BDI-3 Eligibility Evaluation                           11.0   

       Adaptive Developmental Quotient  Adaptive Percentile Rank  \
0                                 85.0                      16.0   
1                                 88.0                      21.0   
2                                 90.0                      25.0   
3                                115.0                      84.0   
4                                 75.0                       5.0   
...                                ...                       ...   
23942                            115.0                      84.0   
23943                            115.0                      84.0   
23944                            103.0                      58.0   
23945                             88.0                      21.0   
23946                            105.0                      63.0   

      Adaptive 95% Confidence Interval         Adaptive RDI Adaptive Z-Score  \
0                                77-97                39/90            1.00   
1                                82-96                79/90            0.80   
2                               81-101                77/90            0.67   
3                              103-123                99/90                1   
4                                68-88  1990-09-01 00:00:00            1.67   
...                                ...                  ...              ...   
23942                          103-123                99/90                1   
23943                          107-121                96/90                1   
23944                           96-110                92/90              0.2   
23945                            82-96                66/90            0.80   
23946                           94-114                94/90             0.33   

       Adaptive T-Score Adaptive NCE  Social-Emotional Sum of Scaled Scores  \
0                  40.0           29                                   29.0   
1                  42.0           33                                   32.0   
2                  43.0           36                                   17.0   
3                  60.0           71                                   21.0   
4                  33.0           15                                   11.0   
...                 ...          ...                                    ...   
23942              60.0           71                                   25.0   
23943     

In [12]:
bdi3_df['Standard Approval'] = bdi3_df['bdi3_df_points'].apply(lambda x: True if x >= 2 else False)
bdi3_df['Extended Approval'] = bdi3_df['BDI-3 Total Developmental Quotient'].apply(lambda x: True if x < 70 else False)
bdi3_df


Child ID Gender Date of Birth Location - Sub Level 1  \
0        44879      F    2022-09-27              Southwest   
1        47795      F    2020-12-23      Greater Nashville   
2        54340      M    2021-06-22        First Tennessee   
3        54344      F    2022-03-07    Southeast Tennessee   
4        54515      M    2021-11-04          Memphis Delta   
...        ...    ...           ...                    ...   
23942  SP03287      F    2023-09-25          Memphis Delta   
23943  SP03288      F    2021-05-18          South Central   
23944  SP03289      F    2021-10-31          South Central   
23945  SP03290      M    2020-03-25          Memphis Delta   
23946  SP03291      M    2023-09-18      Greater Nashville   

                      Program Label  Adaptive Sum of Scaled Scores  \
0      BDI-3 Eligibility Evaluation                            7.0   
1      BDI-3 Eligibility Evaluation                           16.0   
2      BDI-3 Eligibility Evaluation                            8.0   
3      BDI-3 Eligibility Evaluation                           13.0   
4      BDI-3 Eligibility Evaluation                            5.0   
...                             ...                            ...   
23942  BDI-3 Eligibility Evaluation                           13.0   
23943  BDI-3 Eligibility Evaluation                           25.0   
23944  BDI-3 Eligibility Evaluation                           21.0   
23945       BDI-3 Annual Evaluation                           16.0   
23946  BDI-3 Eligibility Evaluation                           11.0   

       Adaptive Developmental Quotient  Adaptive Percentile Rank  \
0                                 85.0                      16.0   
1                                 88.0                      21.0   
2                                 90.0                      25.0   
3                                115.0                      84.0   
4                                 75.0                       5.0   
...                                ...                       ...   
23942                            115.0                      84.0   
23943                            115.0                      84.0   
23944                            103.0                      58.0   
23945                             88.0                      21.0   
23946                            105.0                      63.0   

      Adaptive 95% Confidence Interval         Adaptive RDI Adaptive Z-Score  \
0                                77-97                39/90            1.00   
1                                82-96                79/90            0.80   
2                               81-101                77/90            0.67   
3                              103-123                99/90                1   
4                                68-88  1990-09-01 00:00:00            1.67   
...                                ...                  ...              ...   
23942                          103-123                99/90                1   
23943                          107-121                96/90                1   
23944                           96-110                92/90              0.2   
23945                            82-96                66/90            0.80   
23946                           94-114                94/90             0.33   

       Adaptive T-Score Adaptive NCE  Social-Emotional Sum of Scaled Scores  \
0                  40.0           29                                   29.0   
1                  42.0           33                                   32.0   
2                  43.0           36                                   17.0   
3                  60.0           71                                   21.0   
4                  33.0           15                                   11.0   
...                 ...          ...                                    ...   
23942              60.0           71                                   25.0   
23943     

In [13]:
bdi3_df.loc[(bdi3_df['Standard Approval'] == False) & (bdi3_df['Extended Approval'] == True)]

Empty DataFrame
Columns: [Child ID, Gender, Date of Birth, Location - Sub Level 1, Program Label, Adaptive Sum of Scaled Scores, Adaptive Developmental Quotient, Adaptive Percentile Rank, Adaptive 95% Confidence Interval, Adaptive RDI, Adaptive Z-Score, Adaptive T-Score, Adaptive NCE, Social-Emotional Sum of Scaled Scores, Social-Emotional Developmental Quotient, Social-Emotional Percentile Rank, Social-Emotional 95% Confidence Interval, Social-Emotional RDI, Social-Emotional Z-Score, Social-Emotional T-Score, Social-Emotional NCE, Communication Sum of Scaled Scores, Communication Developmental Quotient, Communication Percentile Rank, Communication 95% Confidence Interval, Communication RDI, Communication Z-Score, Communication T-Score, Communication NCE, Motor Sum of Scaled Scores, Motor Developmental Quotient, Motor Percentile Rank, Motor 95% Confidence Interval, Motor RDI, Motor Z-Score, Motor T-Score, Motor NCE, Cognitive Sum of Scaled Scores, Cognitive Developmental Quotient, Cognitive Percentile Rank, Cognitive 95% Confidence Interval, Cognitive RDI, Cognitive Z-Score, Cognitive T-Score, Cognitive NCE, BDI-3 Total Sum of Scaled Scores, BDI-3 Total Developmental Quotient, BDI-3 Total Percentile Rank, BDI-3 Total 90% Confidence Interval, BDI-3 Total 95% Confidence Interval, BDI-3 Total Z-Score, BDI-3 Total T-Score, BDI-3 Total NCE, Adaptive-Self Care Examiner, Adaptive-Self Care Date of Testing, Adaptive-Self Care RS, Adaptive-Self Care SS, Adaptive-Self Care PR, Adaptive-Self Care AE, Adaptive-Self Care RDI, Adaptive-Self Care CSS, Adaptive-Self Care CSS 90%, Adaptive-Self Care Z-Score, Adaptive-Self Care T-Score, Adaptive-Self Care NCE, Adaptive-Personal Responsibility Examiner, Adaptive-Personal Responsibility Date of Testing, Adaptive-Personal Responsibility RS, Adaptive-Personal Responsibility SS, Adaptive-Personal Responsibility PR, Adaptive-Personal Responsibility AE, Adaptive-Personal Responsibility RDI, Adaptive-Personal Responsibility CSS, Adaptive-Personal Responsibility CSS 90%, Adaptive-Personal Responsibility Z-Score, Adaptive-Personal Responsibility T-Score, Adaptive-Personal Responsibility NCE, Social Emotional-Adult Interaction Examiner, Social Emotional-Adult Interaction Date of Testing, Social Emotional-Adult Interaction RS, Social Emotional-Adult Interaction SS, Social Emotional-Adult Interaction PR, Social Emotional-Adult Interaction AE, Social Emotional-Adult Interaction RDI, Social Emotional-Adult Interaction CSS, Social Emotional-Adult Interaction CSS 90%, Social Emotional-Adult Interaction Z-Score, Social Emotional-Adult Interaction T-Score, Social Emotional-Adult Interaction NCE, Social Emotional-Peer Interaction Examiner, Social Emotional-Peer Interaction Date of Testing, Social Emotional-Peer Interaction RS, Social Emotional-Peer Interaction SS, Social Emotional-Peer Interaction PR, Social Emotional-Peer Interaction AE, Social Emotional-Peer Interaction RDI, Social Emotional-Peer Interaction CSS, Social Emotional-Peer Interaction CSS 90%, Social Emotional-Peer Interaction Z-Score, Social Emotional-Peer Interaction T-Score, ...]
Index: []

Identifying children who scored over 3 total points

In [20]:
three_plus = bdi3_df.loc[bdi3_df['bdi3_df_points'] >= 3]
three_plus['bdi3_df_points'].value_counts()

bdi3_df_points
3     1745
4     1413
5      965
6      903
10     815
8      697
7      638
9      487
Name: count, dtype: int64

In [144]:
sns.histplot(three_plus, x = three_plus['bdi3_df_points'], bins = 7)

<Axes: xlabel='bdi3_df_points', ylabel='Count'>

In [29]:
three = three_plus.loc[three_plus['bdi3_df_points'] == 3]
three

Child ID Gender Date of Birth Location - Sub Level 1  \
8        55077      F    2020-11-23        First Tennessee   
17       56324      F    2022-04-08    Southeast Tennessee   
119     481946      M    2020-01-15              Southwest   
120     481946      M    2020-01-15              Southwest   
155     483662      F    2020-02-29          South Central   
...        ...    ...           ...                    ...   
23890  SP03235      F    2022-10-25         East Tennessee   
23893  SP03238      M    2022-09-21         East Tennessee   
23901  SP03246      M    2022-01-21         East Tennessee   
23907  SP03252      F    2022-09-15          Memphis Delta   
23935  SP03280      M    2023-04-16       Upper Cumberland   

                      Program Label  Adaptive Sum of Scaled Scores  \
8      BDI-3 Eligibility Evaluation                            7.0   
17     BDI-3 Eligibility Evaluation                            9.0   
119         BDI-3 Annual Evaluation                           17.0   
120         BDI-3 Annual Evaluation                           17.0   
155         BDI-3 Annual Evaluation                           19.0   
...                             ...                            ...   
23890  BDI-3 Eligibility Evaluation                            6.0   
23893  BDI-3 Eligibility Evaluation                            1.0   
23901  BDI-3 Eligibility Evaluation                            9.0   
23907  BDI-3 Eligibility Evaluation                           13.0   
23935  BDI-3 Eligibility Evaluation                            4.0   

       Adaptive Developmental Quotient  Adaptive Percentile Rank  \
8                                 61.0                       1.0   
17                                95.0                      37.0   
119                               91.0                      27.0   
120                               91.0                      27.0   
155                               97.0                      42.0   
...                                ...                       ...   
23890                             80.0                       9.0   
23893                             55.0                       0.0   
23901                             95.0                      37.0   
23907                            115.0                      84.0   
23935                             70.0                       2.0   

      Adaptive 95% Confidence Interval         Adaptive RDI Adaptive Z-Score  \
8                                56-70                21/90            2.60   
17                              86-106                82/90            0.33   
119                              85-99                79/90            0.60   
120                              85-99                79/90            0.60   
155                             90-104                88/90            0.20   
...                                ...                  ...              ...   
23890                            73-93  1990-09-01 00:00:00            1.33   
23893                            51-71                <1/90            3.00   
23901                           86-106                82/90            0.33   
23907                          103-123                99/90                1   
23935                            64-84  1990-03-01 00:00:00            2.00   

       Adaptive T-Score Adaptive NCE  Social-Emotional Sum of Scaled Scores  \
8                  24.0           <1                                   27.0   
17                 47.0           43                                   13.0   
119                44.0           37                                   31.0   
120                44.0           37                                   31.0   
155                48.0           46                                   26.0   
...                 ...          ...                                    ...   
23890              37.0           22                                   11.0   
23893     

In [34]:
sk_1 = bdi3_df.groupby(['Standard Approval', 'Extended Approval'])['Child ID'].count().reset_index()
sk_1.columns = ['source', 'target', 'value']

In [35]:
sk_1

source  target  value
0   False   False  12297
1    True   False   7853
2    True    True   3797

In [ ]:
#points_cols 

In [50]:
adaptive_points = bdi3_df['Adaptive DQ Points'].value_counts().reset_index()

In [60]:
adaptive_points['point_type'] = 'Adaptive'
adaptive_points = adaptive_points.rename(columns = {'Adaptive DQ Points': 'points'})

In [61]:
social_emo_points = bdi3_df['Social-Emotional DQ Points'].value_counts().reset_index()
social_emo_points['point_type'] = 'Social-Emotional'
social_emo_points = social_emo_points.rename(columns = {'Social-Emotional DQ Points': 'points'})

In [62]:
comm_points = bdi3_df['Communication DQ Points'].value_counts().reset_index()
comm_points['point_type'] = 'Communication'
comm_points = comm_points.rename(columns = {'Communication DQ Points': 'points'})

In [63]:
motor_points = bdi3_df['Motor DQ Points'].value_counts().reset_index()
motor_points['point_type'] = 'Motor'
motor_points = motor_points = motor_points.rename(columns = {'Motor DQ Points': 'points'})

In [64]:
cog_points = bdi3_df['Cognitive DQ Points'].value_counts().reset_index()
cog_points['point_type'] = 'Cognitive'
cog_points = cog_points.rename(columns = {'Cognitive DQ Points': 'points'})

In [66]:
points_df = pd.concat([adaptive_points, social_emo_points, comm_points, motor_points, cog_points], axis = 0)
points_df

points  count        point_type
0       0  17315          Adaptive
1       2   4708          Adaptive
2       1   1924          Adaptive
0       0  19773  Social-Emotional
1       2   2176  Social-Emotional
2       1   1998  Social-Emotional
0       0  12681     Communication
1       2   8885     Communication
2       1   2381     Communication
0       0  19977             Motor
1       2   2591             Motor
2       1   1379             Motor
0       0  17901         Cognitive
1       2   3464         Cognitive
2       1   2582         Cognitive

In [145]:
sns.catplot(
    points_df, kind='bar',
    x = 'points', y='count', col = 'point_type',
    height = 4, aspect = .5)


C:\Users\rose\anaconda3\Lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)


In [99]:
adaptive_points = three_plus['Adaptive DQ Points'].value_counts().reset_index()
adaptive_points['point_type'] = 'Adaptive'
adaptive_points = adaptive_points.rename(columns = {'Adaptive DQ Points': 'points'})

social_emo_points = three_plus['Social-Emotional DQ Points'].value_counts().reset_index()
social_emo_points['point_type'] = 'Social-Emotional'
social_emo_points = social_emo_points.rename(columns = {'Social-Emotional DQ Points': 'points'})

comm_points = three_plus['Communication DQ Points'].value_counts().reset_index()
comm_points['point_type'] = 'Communication'
comm_points = comm_points.rename(columns = {'Communication DQ Points': 'points'})

motor_points = three_plus['Motor DQ Points'].value_counts().reset_index()
motor_points['point_type'] = 'Motor'
motor_points = motor_points = motor_points.rename(columns = {'Motor DQ Points': 'points'})

cog_points = three_plus['Cognitive DQ Points'].value_counts().reset_index()
cog_points['point_type'] = 'Cognitive'
cog_points = cog_points.rename(columns = {'Cognitive DQ Points': 'points'})

three_points_df = pd.concat([adaptive_points, social_emo_points, comm_points, motor_points, cog_points], axis = 0)
three_points_df

points  count        point_type
0       2   3977          Adaptive
1       0   2401          Adaptive
2       1   1285          Adaptive
0       0   3757  Social-Emotional
1       2   2138  Social-Emotional
2       1   1768  Social-Emotional
0       2   6516     Communication
1       1    590     Communication
2       0    557     Communication
0       0   4134             Motor
1       2   2472             Motor
2       1   1057             Motor
0       2   3365         Cognitive
1       0   2229         Cognitive
2       1   2069         Cognitive

In [91]:
sns.catplot(
    three_points_df, kind='bar',
    x = 'points', y='count', col = 'point_type',
    height = 4, aspect = .5)

C:\Users\rose\anaconda3\Lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)


In [93]:
four_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 4]
five_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 5]
six_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 6]
seven_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 7]
eight_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 8]
nine_pt = bdi3_df.loc[bdi3_df['bdi3_df_points'] == 9]

In [129]:
def points_func(df):

        adaptive_points = df['Adaptive DQ Points'].value_counts().reset_index()
        adaptive_points['point_type'] = 'Adaptive'
        adaptive_points = adaptive_points.rename(columns = {'Adaptive DQ Points': 'points'})
        

        social_emo_points = df['Social-Emotional DQ Points'].value_counts().reset_index()
        social_emo_points['point_type'] = 'Social-Emotional'
        social_emo_points = social_emo_points.rename(columns = {'Social-Emotional DQ Points': 'points'})
        


        comm_points = df['Communication DQ Points'].value_counts().reset_index()
        comm_points['point_type'] = 'Communication'
        comm_points = comm_points.rename(columns = {'Communication DQ Points': 'points'})
        

        motor_points = df['Motor DQ Points'].value_counts().reset_index()
        motor_points['point_type'] = 'Motor'
        motor_points = motor_points = motor_points.rename(columns = {'Motor DQ Points': 'points'})
        

        cog_points = df['Cognitive DQ Points'].value_counts().reset_index()
        cog_points['point_type'] = 'Cognitive'
        cog_points = cog_points.rename(columns = {'Cognitive DQ Points': 'points'})
        

        end_df = pd.concat([adaptive_points, social_emo_points, comm_points, motor_points, cog_points], axis = 0)
        return end_df

In [130]:
four_df = points_func(four_pt)
five_df = points_func(five_pt)
six_df = points_func(six_pt)
seven_df = points_func(seven_pt)
eight_df = points_func(eight_pt)
nine_df = points_func(nine_pt)

In [137]:
four_df['total_points_per_child'] = 4
five_df['total_points_per_child'] = 5
six_df['total_points_per_child'] = 6
seven_df['total_points_per_child'] = 7
eight_df['total_points_per_child'] = 8
nine_df['total_points_per_child'] = 9
three_points_df['total_points_per_child'] = 3

In [138]:
three_thru_nine_pts = pd.concat([three_points_df, four_df, five_df, six_df, seven_df, eight_df, nine_df], axis = 0)

In [139]:
three_thru_nine_pts

points  count        point_type  total_points_per_child
0        2   3977          Adaptive                       3
1        0   2401          Adaptive                       3
2        1   1285          Adaptive                       3
0        0   3757  Social-Emotional                       3
1        2   2138  Social-Emotional                       3
..     ...    ...               ...                     ...
1        1      7     Communication                       9
0        2    373             Motor                       9
1        1    114             Motor                       9
0        2    432         Cognitive                       9
1        1     55         Cognitive                       9

[100 rows x 4 columns]

In [140]:
sns.catplot(
    three_thru_nine_pts, kind='bar',
    x = 'points', y='count', col = 'point_type', row = 'total_points_per_child',
    height = 4, aspect = .5)

C:\Users\rose\anaconda3\Lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)


In [160]:
standard_counts = bdi3_df['Standard Approval'].value_counts().reset_index()
standard_counts = standard_counts.rename(columns = {'Standard Approval': 'Eligibility', 'count':'Child Count'})
standard_counts['Eligibility Type'] = 'Standard'
standard_counts

Eligibility  Child Count Eligibility Type
0        False        12297         Standard
1         True        11650         Standard

In [161]:
extended_counts = bdi3_df['Extended Approval'].value_counts().reset_index()
extended_counts = standard_counts.rename(columns = {'Extended Approval': 'Extended', 'count':'Child Count'})
extended_counts['Eligibility Type'] = 'Extended'
extended_counts

Eligibility  Child Count Eligibility Type
0        False        12297         Extended
1         True        11650         Extended

In [162]:
len(bdi3_df.loc[(bdi3_df['Standard Approval'] == True) & (bdi3_df['Extended Approval'] == False)])

7853

There are 7853 students who are eligible under the standar approval but not the Extended approval, but none who would meet the Extended approval and not the standard. 11650 students qualify under Standard Approval and 3797 under the Extended approval

In [163]:
len(bdi3_df.loc[(bdi3_df['Standard Approval'] == False) & (bdi3_df['Extended Approval'] == True)])

0

In [164]:
approval_counts = pd.concat([standard_counts, extended_counts], axis=0)
approval_counts = approval_counts.loc[approval_counts['Eligibility'] == True]

Categories: Standard, Extended
Subcategories: Standard: Eligible due to two points in one domains, 
                         Eligible due to one point in two domains
                         Eligible from BOTH
               Extended: Eligible from BDI3 total?

In [ ]:
#How do I want to go about this? I have a DQ Points column for each domain. The max points in a column is TWO. If thye have at least one 2 and a total score of 4 they qualify either way